api.key=sk-ws-H.PEMIYLX.YgFY.MEUCIQCb7V5DVxR6HGlzeGBL_LxM5-DwSk8TQgpAtZ0kF1qvqwIgE8-LZj5mD9bQXzw8CqdcBztXPrIL-Jg7WSdXMRVedGE
api.url=https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions
model.name=q-7b-instruct